filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true 
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    tests:
        override:
            -
                command: 'tools/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'php-clover'

    dependencies:
        before:
            - 'wget https://phar.io/releases/phive.phar'
            - 'php phive.phar install --trust-gpg-keys 4AA394086372C20A'
    environment:
        php:
            version: 5.6.9
tools:
    php_sim: false
    php_cpd: false